version: '3.8'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'

  prod:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '8080:8080'
    command: npm run start
    environment:
      NODE_ENV: production
    depends_on:
      - redis
    restart: always

  client:
    build:
      context: ../frontend/AutoZoomV2
      dockerfile: Dockerfile
    ports:
      - '8001:8000'
    user: '1000:1000' # Add this line to set the user and group permissions

