version: '3.8'

services:
  prod:
    image: danieled1/autozoommanager-server:latest
    volumes:
      - .:/app
      # - /app/node_modules
    ports:
      - '8080:8080'
    command: npm run start
    environment:
      NODE_ENV: production
    restart: always

  client:
    image: danieled1/autozoommanager-frontend:latest
    ports:
      - '8001:8000'
    user: '1000:1000' # Add this line to set the user and group permissions
  # dev:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: dev
  #   volumes:
  #     - .:/app
  #     # - /app/node_modules
  #   ports:
  #     - '8081:8081'
  #   command: npm run dev
  #   environment:
  #     NODE_ENV: development
  #   restart: always
