name: Build and run Docker containers

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Cache frontend dependencies
        id: cache-frontend
        uses: actions/cache@v2
        with:
          path: frontend/AutoZoomV2/node_modules # Path to the frontend dependencies
          key: ${{ runner.os }}-frontend-${{ hashFiles('frontend/AutoZoomV2/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-

      - name: Cache server dependencies
        id: cache-server
        uses: actions/cache@v2
        with:
          path: server-to-server-oauth-starter-api-main/node_modules # Path to the server dependencies
          key: ${{ runner.os }}-server-${{ hashFiles('server-to-server-oauth-starter-api-main/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-server-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push frontend
        id: docker_build_frontend
        uses: docker/build-push-action@v2
        with:
          context: ./frontend/AutoZoomV2
          push: true
          tags: danieled1/autozoommanager-frontend:latest
          cache-from: type=local,src=/tmp/.buildx-cache-frontend
          cache-to: type=local,dest=/tmp/.buildx-cache-frontend

      - name: Build and push server
        id: docker_build_server
        uses: docker/build-push-action@v2
        with:
          context: ./server-to-server-oauth-starter-api-main
          push: true
          tags: danieled1/autozoommanager-server:latest
          cache-from: type=local,src=/tmp/.buildx-cache-server
          cache-to: type=local,dest=/tmp/.buildx-cache-server

      - name: Image digest (frontend)
        run: echo "DOCKER_IMAGE_DIGEST_FRONTEND=${{ steps.docker_build_frontend.outputs.digest }}" >> $GITHUB_ENV

      - name: Image digest (server)
        run: echo "DOCKER_IMAGE_DIGEST_SERVER=${{ steps.docker_build_server.outputs.digest }}" >> $GITHUB_ENV

      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/AutoZoom/server-to-server-oauth-starter-api-main
            git pull
            docker-compose pull
            docker-compose up -d
